#!/bin/bash -eu

workspaceDir="$1"
outputPath="$2"

hasCopied=0
isDirTgt=0

if [[ -d "$outputPath" ]] ; then
    isDirTgt=1
fi

function assertCollision() {
    if [[ $hasCopied -gt 0 && $isDirTgt -eq 0 ]] ; then
        echo "goto Error: Multiple binaries for file-type output " \
             "target: $outputPath" >&2
        exit 1
    fi
}

function copySafe() {
    local binSrc="$1"
    local binBase=$(basename "$binSrc")
    if [[ $isDirTgt -gt 0 && -d "$outputPath/$binBase" ]] ; then
        echo "Goto warning: Skipping binary export. $binBase conflicts with" \
             "directory at $outputPath/$binBase/" >&2
    else
        cp $binSrc $outputPath
    fi
}

if [[ -d "$workspaceDir/bin/" ]] ; then
    shopt -s nullglob

    for binSrc in $workspaceDir/bin/* ; do
        assertCollision
        copySafe "$binSrc"
        hasCopied=1
    done
fi
    
