#!/bin/bash -eu

cntxArg="$1"
tgtArg="$2"

if [[ ! -z "$cntxArg" ]] ; then
    tgtArg="$cntxArg"
fi

. libGoCmds.sh

buildPath=$(maskGoWilds "$tgtArg")
buildDir=$(fileToPackage "$buildPath")

if [[ -e "$buildDir" ]] ; then
    echo "$buildDir"
    
else
    if [[ -z "$cntxArg" ]] ; then
        echo "goto Warning: Target ($tgtArg) is not a filesystem path." \
             "Using current working directory for project context" >&2
        pwd

    else
        echo "goto Error: Specified context directory does not exist" \
             "$cntxArg" >&2
        exit 1
    fi
fi
