#!/bin/bash -eu

workspaceDir=$1;
shift; subPathArg=$@

function selectSubPath() {
    if [[ $# -eq 0 ]] ; then
	echo root
    else
	echo $1
    fi
}

function sanitizeWorkspacePath() {
    local workspaceDir=$1
    readlink -f $workspaceDir
}

subPath=$(selectSubPath $subPathArg)
sanitWork=$(sanitizeWorkspacePath $workspaceDir)

: "${GOPATH:=}"
export GOPATH

if [[ -z $GOPATH ]] ; then
    export GOPATH=$sanitWork
else
    export GOPATH=$sanitWork:$GOPATH
fi

go install $subPath
