#!/bin/bash -eu

goCall="$1"
workspaceDir="$2"
subPath="$3"

if [[ -z "$subPath" ]] ; then
    subPath=root
fi

sanitWork=$(readlink -f "$workspaceDir")

: "${GOPATH:=}"
export GOPATH

if [[ -z "$GOPATH" ]] ; then
    export GOPATH="$sanitWork"
else
    export GOPATH="$sanitWork:$GOPATH"
fi

go $goCall "$subPath"
