#!/bin/bash -eu

goCall="$1"
workspaceDir="$2"
goTgt="$3"

sanitWork=$(readlink -f "$workspaceDir")

: "${GOPATH:=}"
export GOPATH

if [[ -z "$GOPATH" ]] ; then
    export GOPATH="$sanitWork"
else
    export GOPATH="$sanitWork:$GOPATH"
fi

go $goCall "$goTgt"
