#!/bin/bash -eu

scriptDir=$(dirname $(readlink -f $0))
export PATH=$PATH:$scriptDir/

if trapHelpMsg $@ ; then
    exit
fi

outputPath=.
goCmd=install
goCmdFlags=""
while getopts "ct:o:f:" opt ; do
    case $opt in
        o) outputPath="$OPTARG";;
        c) goCmd=$OPTARG;;
        t) goCmd=test;;
        r) goCmd=run
        f) goCmdFlags="$OPTARG";;
    esac
done

shift $(($OPTIND - 1))
if [[ $# -eq 0 ]] ; then
    buildDir="$PWD"
else
    buildDir="$1"
fi

. dirLayout

projectDir=$(discoverProject $buildDir)
subPath=$(breakOffBuildSub $projectDir $buildDir)

workDir=$(setupWorkDir $projectDir)
setWorkDirs $workDir

includeProject $projectDir $localSrc
federateWorkspace

installGoTarget $federatedWorkspace $subPath
exportBinaries $federatedWorkspace $outputPath
