#!/bin/bash -eu

scriptDir=$(dirname $(readlink -f $0))
export PATH=$PATH:$scriptDir/

if trapHelpMsg $@ ; then
    exit
fi

outputPath=.
goCmd=install
goCmdFlags=""
while getopts "o:tbc:f:" opt ; do
    case $opt in
        o) outputPath="$OPTARG";;
        c) goCmd=$OPTARG;;
        t) goCmd=test;;
        b) goCmd=build;;
        f) goCmdFlags="$OPTARG";;
    esac
done

shift $(($OPTIND - 1))
if [[ $# -eq 0 ]] ; then
    buildDir="$PWD"
else
    buildDir="$1"
fi

. dirLayout

projectDir=$(discoverProject "$buildDir")
subPath=$(breakOffBuildSub "$projectDir" "$buildDir")

workDir=$(setupWorkDir "$projectDir")
setWorkDirs "$workDir"

includeProject "$projectDir" "$localSrc"
federateWorkspace

goCall="$goCmd $goCmdFlags"

installGoTarget "$goCall" "$federatedWorkspace" "$subPath"
exportBinaries "$federatedWorkspace" "$outputPath"
