#!/bin/bash -eu

scriptDir=$(dirname $(readlink -f $0))
export PATH=$PATH:$scriptDir/

if trapHelpMsg $@ ; then
    exit
fi

outputPath=.
goCmd=install
goCmdFlags=""
cntxDir=""

while getopts "o:tbc:f:C:" opt ; do
    case $opt in
        o) outputPath="$OPTARG";;
        c) goCmd=$OPTARG;;
        t) goCmd=test;;
        b) goCmd=build;;
        f) goCmdFlags="$OPTARG";;
        C) cntxDir="$OPTARG";;
    esac
done

shift $(($OPTIND - 1))
if [[ $# -eq 0 ]] ; then
    buildTgt="$PWD"
else
    buildTgt="$1"
fi

. libDirLayout.sh

buildDir=$(inferBuildDir "$cntxDir" "$buildTgt")
projectDir=$(discoverProject "$buildDir")

goCall="$goCmd $goCmdFlags"
goTgt=$(translateGoTgt "$projectDir" "$buildTgt")

workDir=$(setupWorkDir "$projectDir")
setWorkDirs "$workDir"

includeProject "$projectDir" "$localSrc"
federateWorkspace

installGoTarget "$goCall" "$federatedWorkspace" "$goTgt"
exportBinaries "$federatedWorkspace" "$outputPath"
