#!/bin/bash -eu

projectDir="$1"
buildTgt="$2"

. libGoCmds.sh

function isPathTgt() {
    local tgt="$1"
    local pathTgt=$(maskGoWilds "$tgt")
    [[ -e $pathTgt ]]
}

function rerefPath() {
    set -e
    local tgt="$1"
    local path=$(maskGoWilds "$tgt")
    local subPath
    subPath=$(breakOffBuildSub "$projectDir" "$path")
    addBackGoWilds "$tgt" "$subPath"
}

function rerefProjectPath() {
    local tgt="$1"
    if isPathTgt "$tgt" ; then
        rerefPath "$tgt"
    else
        echo "$tgt"
    fi
}

function prepPathTgt() {
    dirTgt=$(fileToPackage "$1")
    rerefProjectPath "$dirTgt"
}

refTgt=$(prepPathTgt "$buildTgt")
sanitizePackage "$refTgt"
