#!/bin/bash -eu

projectDir="$1"
buildTgt="$2"

. libGoCmds.sh

function isPathTgt() {
    local tgt="$1"
    local pathTgt=$(maskGoWilds "$tgt")
    [[ -e $pathTgt ]]
}

function rerefPath() {
    local tgt="$1"
    local path=$(maskGoWilds "$tgt")
    local subPath=$(breakOffBuildSub "$projectDir" "$path")
    addBackWilds "$tgt" "$subPath"
}

function addBackWilds() {
    local origArg="$1"
    local subPath="$2"
    if [[ "$origArg" != $(maskGoWilds "$origArg") ]] ; then
        addGoWild "$subPath"
    else
        echo "$subPath"
    fi
}

function rerefProjectPath() {
    local tgt="$1"
    if isPathTgt "$tgt" ; then
        rerefPath "$tgt"
    else
        echo "$tgt"
    fi
}

function prepPathTgt() {
    dirTgt=$(fileToPackage "$1")
    rerefProjectPath "$dirTgt"
}

refTgt=$(prepPathTgt "$buildTgt")
sanitizePackage "$refTgt"
